## Introduction to Julia

_STFC-Rutherford Appleton Laboratory, England_

_Thursday December 8, 2022_

**_Alexis Montoison_** (alexis.montoison@polymtl.ca)

* How to use Julia
* Basic syntax and types
* Control flow
* Functions
* More on types
* Linear algebra
* Package management
* Advanced features

## How to use Julia

### REPL

The Read-Eval-Print-Loop (REPL) is the julia interactive shell

```bash
julia
```

<img src="img/REPL.png">

### Command line

You can execute a julia script from the command line
```bash
julia script.jl
```

To pass command line arguments
```bash
julia script.jl arg1 arg2 arg3
```
Command-line arguments are accessed within julia via the variable `ARGS`.

### Jupyter

Julia is the "Ju" in "Jupyter"!

To run Julia in a notebook:

* Install Jupyter (e.g. via Anaconda)
* Install the `IJulia` package
* Launch Jupyter

(if you skip the Jupyter installation, Julia will install a julia-only `conda` distribution)

## Basic syntax and types

### Basic types

Booleans

In [353]:
true

true

In [354]:
typeof(true)

Bool

Integers

In [355]:
1 + 1

2

In [356]:
typeof(1)

Int64

Floating point

In [357]:
1.0 + 2.0

3.0

In [358]:
typeof(1.0)

Float64

Floating-point arithmetic has limited precision!

In [359]:
(1.0 + 1e-16) == 1.0

true

In [360]:
(1.0 + 1e-16) - 1e-16 == 1.0 + (1e-16 - 1e-16)

false

Type correspondence:

| Julia   | C       |
|:-------:|:-------:|
| Int32   | int     |
| Int64   | long    | 
| Float32 | float   |
| Float64 | double  |

Strings are defined with double quotes

In [361]:
"Hello world!"

"Hello world!"

Concatenate strings with `*`

In [362]:
"Hello" * " " * "world!"

"Hello world!"

String interpolation eases the need for concatenation

In [363]:
x, y, z = "Alice", "Bob", "Charles"
"Hello $(x), $y and $(z)!"

"Hello Alice, Bob and Charles!"

Symbols are human-readable unique identifiers

In [364]:
:symbol
typeof(:symbol)

Symbol

### Elementary data structures

Tuples are immutable collections of values

In [365]:
t1 = (1, 2, 3)
t2 = ("hello", 1, :x)

("hello", 1, :x)

In [366]:
typeof(t1)

Tuple{Int64, Int64, Int64}

In [367]:
typeof(t2)

Tuple{String, Int64, Symbol}

Arrays are collections of values **of the same type** that are stored contiguously in memory.

In [368]:
u = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [369]:
typeof(u)

Vector{Int64} (alias for Array{Int64, 1})

**/!\ Array indexing starts at 1 /!\**

In [370]:
u[1]

1

Elements automatically get promoted to the same type if necessary

In [371]:
v = [1.0, 2, 3]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [372]:
typeof(v)

Vector{Float64} (alias for Array{Float64, 1})

If no common type can be inferred, the element type is `Any`

In [373]:
w = ["hello", 1, :x]

3-element Vector{Any}:
  "hello"
 1
  :x

In [374]:
typeof(w)

Vector{Any} (alias for Array{Any, 1})

Dictionnaries

In [375]:
d = Dict("a" => 1, "b" => 2, "c" => 3)

Dict{String, Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 1

In [376]:
d["a"]

1

In [377]:
d["a"] = 2
d

Dict{String, Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 2

In [378]:
d["d"] = 4

4

## Control flow

### If-then-else

In [379]:
if x == 0
    println("Hello 0!")
elseif x == 1
    println("Hello 1!")
elseif x == -1
    println("Hello -1!")
else
    println("Hello x")
end 

Hello x


### For loops

In [380]:
for i in 1:5
    println("Hello $(i)!")
end

Hello 1!
Hello 2!
Hello 3!
Hello 4!
Hello 5!


Iterate over arrays

In [381]:
u = [1, 4, 9, 16]
for x in u
    println(x)
end

1
4
9
16


Iterate over dictionnaries

In [382]:
d = Dict("a" => 1, "b" => 2, "c" => 3)
for (key, val) in d
    println("Key: $key, val: $val")
end

Key: c, val: 3
Key: b, val: 2
Key: a, val: 1


More generally: **iterate over any collection**

### Comprehensions

Build a list of increasing integers

In [383]:
u = [i for i in 1:4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [384]:
v = [1 for _ in 1:4]

4-element Vector{Int64}:
 1
 1
 1
 1

Build a matrix

In [385]:
A = [i*j for i in 1:4, j in 1:4]

4×4 Matrix{Int64}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

Filter out some values

In [386]:
v = [i for i in 1:10 if i % 2 == 1]  # odd integers between 1 and 10

5-element Vector{Int64}:
 1
 3
 5
 7
 9

Dictionnaries

In [387]:
d = Dict("$i" => i^2 for i in 1:5)

Dict{String, Int64} with 5 entries:
  "4" => 16
  "1" => 1
  "5" => 25
  "2" => 4
  "3" => 9

## Functions

To define a function:

In [388]:
function print_hello()
    println("Hello world!")
end
print_hello()

Hello world!


Functions can have arguments

In [389]:
function print_it(x, y)
    println(x)
    println(y)
end
print_it("Hello", 1)
print_it([1, 2], 47.0)

Hello
1
[1, 2]
47.0


Optional arguments are possible

In [390]:
function print_info(x; prefix="Value : ")
    println("$(prefix)$x")
end
print_info(3.1415)
print_info(3.1415, prefix="π = ")

Value : 3.1415
π = 3.1415


The return value of a function is specified with the keyword `return`

In [391]:
function my_mul(x, y)
    return x * y
end
my_mul(1, 2)

2

Otherwise, the function returns the result of the last expression

Docstrings are written before the body of the function, and start/end with `"""`.
You can use Markdown syntax within docstrings.

In [392]:
"""
    my_mul(x, y, z)

Compute the product `x*y*z`
"""
function my_mul(x, y, z)
    return x * y * z
end

my_mul

Always write docstrings!

### Getting help

You can display a function's docstring by pre-prending `?` to its name

In [393]:
?my_mul

search: my_mul



```
my_mul(x, y, z)
```

Compute the product `x*y*z`


## More on types

Everything in Julia has a type.

You don't **need** to specify types when declaring variables or function arguments... but sometimes it helps.

To avoid errors

In [394]:
"""
    my_fact(n)

Compute the factorial of `n`, i.e., `1*2*...*(n-1)*n`.
"""
function my_fact(n)
    if n == 1
        return 1
    else
        return n * my_fact(n - 1)
    end
end
my_fact(10)

3628800

In [395]:
my_fact(1.5)

LoadError: StackOverflowError:

## Declaring your own types

### Abstract types

In [396]:
abstract type AbstractFoo end

Abstract types
* cannot have attributes
* cannot be instantiated

In [397]:
AbstractFoo()

LoadError: MethodError: no constructors have been defined for AbstractFoo

### Immutable types

are called `struct` in Julia (like C)

In [398]:
struct Foo
    x
end

In [399]:
foo = Foo(1.0)

Foo(1.0)

You cannot modify the attributes of an `immutable` type

In [400]:
foo.x = 2

LoadError: setfield!: immutable struct of type Foo cannot be changed

### Mutable types

are `struct`s whose attributes can be modified.

In [401]:
mutable struct FooBar
    x
end

In [402]:
foo = FooBar(1.0)
typeof(foo)

FooBar

In [403]:
foo.x = 2

2

### Parametrized types

Types can be parametrized by other types

In [404]:
Vector

Vector (alias for Array{T, 1} where T)

You can parametrize by multiple types

In [405]:
struct MyFoo{Ti<:Integer, Tv<:AbstractFloat}
    i::Ti
    v::Tv
end
typeof(MyFoo(1, 1.0))

MyFoo{Int64, Float64}

In [406]:
typeof(MyFoo(0x01, 1.0f0))

MyFoo{UInt8, Float32}

### What about functions?

Functions are not "attached" to classes like in object-oriented languages.

Functions have _methods_ that are dispatched based on the types of **all** arguments: it's called **multiple dispatch**

In [407]:
@which +(1.0, 1.0)

+(x::T, y::T) where T<:Union{Float16, Float32, Float64} in Base at float.jl:383

In [408]:
@which +(1.0, 1)

+(x::Number, y::Number) in Base at promotion.jl:388

In [409]:
+

+ (generic function with 206 methods)

In [410]:
methods(+)

# 206 methods for generic function "+":
[1] +(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:87
[2] +(x::T, y::T) where T<:Union{Float16, Float32, Float64} in Base at float.jl:383
[3] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigInt) in Base.GMP at gmp.jl:531
[4] +(c::Union{Int16, Int32, Int64, Int8}, x::BigInt) in Base.GMP at gmp.jl:537
[5] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigFloat) in Base.MPFR at mpfr.jl:398
[6] +(c::Union{Int16, Int32, Int64, Int8}, x::BigFloat) in Base.MPFR at mpfr.jl:406
[7] +(c::Union{Float16, Float32, Float64}, x::BigFloat) in Base.MPFR at mpfr.jl:414
[8] +(x::Union{Dates.CompoundPeriod, Dates.Period}) in Dates at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/Dates/src/periods.jl:378
[9] +(r1::StepRangeLen{T, R}, r2::StepRangeLen{T, R}) where {R<:Base.TwicePrecision, T} in Base at twiceprecision.jl:644
[10] +(r1::StepRangeLen{T, S}, r2::StepRangeLen{T, S}) where {T, S} in Base at range.jl:1446
[11] +(F::Hessenberg, J::UniformScaling) in LinearAlgebra at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/LinearAlgebra/src/hessenberg.jl:641
[12] +(A::Symmetric, B::Symmetric) in LinearAlgebra at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:469
[13] +(A::Symmetric, B::SymTridiagonal) in LinearAlgebra at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:486
[14] +(S::Symmetric, D::Diagonal) in LinearAlgebra at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:191
[15] +(A::Symmetric{<:Any, <:AbstractSparseMatrix}, B::AbstractSparseMatrix) in SparseArrays at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/SparseArrays/src/linalg.jl:15
[16] +(A::Symmetric, B::AbstractSparseMatrix) in SparseArrays at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/SparseArrays/src/linalg.jl:18
[17] +(A::Symmetric{<:Real, <:AbstractSparseMatrix}, B::Hermitian{<:Any, <:AbstractSparseMatrix}) in SparseArrays at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/SparseArrays/src/linalg.jl:25
[18] +(A::Symmetric{var"#s884", S} where {var"#s884"<:Real, S<:(AbstractMatrix{<:var"#s884"})}, B::Hermitian) in LinearAlgebra at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:484
[19] +(A::Symmetric{<:Any, <:AbstractSparseMatrix}, B::Hermitian{<:Any, <:AbstractSparseMatrix}) in SparseArrays at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/SparseArrays/src/linalg.jl:23
[20] +(x::T, y::Integer) where T<:AbstractChar in Base at char.jl:237
[21] +(A::SparseArrays.AbstractSparseMatrixCSC, B::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/SparseArrays/src/sparsematrix.jl:1829
[22] +(A::SparseArrays.AbstractSparseMatrixCSC, B::Array) in SparseArrays at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/SparseArrays/src/sparsematrix.jl:1832
[23] +(A::SparseArrays.AbstractSparseMatrixCSC, J::UniformScaling) in SparseArrays at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/SparseArrays/src/sparsematrix.jl:3821
[24] +(y::AbstractFloat, x::Bool) in Base at bool.jl:172
[25] +(r1::OrdinalRange, r2::OrdinalRange) in Base at range.jl:1423
[26] +(A::BitArray, B::BitArray) in Base at bitarray.jl:1184
[27] +(x::Base.TwicePrecision, y::Number) in Base at twiceprecision.jl:290
[28] +(x::Base.TwicePrecision{T}, y::Base.TwicePrecision{T}) where T in Base at twiceprecision.jl:296
[29] +(x::Base.TwicePrecision, y::Base.TwicePrecision) in Base at twiceprecision.jl:301
[30] +(A::UnitLowerTriangular, B::LowerTriangular) in LinearAlgebra at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/LinearAlgebra/src/triangular.jl:643
[31] +(A::UnitLowerTriangular, B::UnitLowerTriangular) in LinearAlgebra at /home/alexis/julia/julia-1.8.3/share/julia/stdlib/v1.8/LinearAlgebra/src/triangular.jl:645
[32] +(UL::UnitLowerTriang

## Linear algebra

To use linear algebra functions, use the `LinearAlgebra` package (part of the standard library)

In [411]:
using LinearAlgebra

### Vectors and Matrices

A vector is a uni-dimensional array

In [412]:
Vector{Float32}

Vector{Float32} (alias for Array{Float32, 1})

In [413]:
x = [1.0, 2.0]

2-element Vector{Float64}:
 1.0
 2.0

A matrix is a two-dimensional array

In [414]:
Matrix{Float64}

Matrix{Float64} (alias for Array{Float64, 2})

In [415]:
A = [
    1.0 2.0;
    3.0 4.0
]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

### Linear algebra operations

Matrix-vector products work out of the box

In [416]:
A * x  # mul!(y, A, x) for an in-place variant

2-element Vector{Float64}:
  5.0
 11.0

Solve linear systems

In [417]:
b = A * x
y = A \ b

2-element Vector{Float64}:
 1.0
 2.0

You can't multiply two vectors

In [418]:
x * x

LoadError: MethodError: no method matching *(::Vector{Float64}, ::Vector{Float64})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:591
  *(::StridedMatrix{T}, ::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF32, ComplexF64}, S<:Real} at ~/julia/julia-1.8.3/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:49
  *(::StridedVecOrMat, ::Adjoint{<:Any, <:LinearAlgebra.LQPackedQ}) at ~/julia/julia-1.8.3/share/julia/stdlib/v1.8/LinearAlgebra/src/lq.jl:269
  ...

But inner and outer product is OK

In [419]:
x' * x  # inner product

5.0

In [420]:
x * x'  # outer product

2×2 Matrix{Float64}:
 1.0  2.0
 2.0  4.0

### BLAS / LAPACK

For real/complex numbers in `Float32`, `Float64` precision:
* dense vector-vector, matrix-vector, matrix-matrix operations call BLAS
* dense matrix factorizations call LAPACK

You can also call BLAS/LAPACK functions directly

In [421]:
C = zeros(2, 2);
A = ones(2, 4);
BLAS.syrk!('U', 'N', 1.0, A, 0.0, C)  # computes C = α A*A' + β C

2×2 Matrix{Float64}:
 4.0  4.0
 0.0  4.0

### Sparse linear algebra

In [422]:
using SparseArrays

In [423]:
A = sparse([1, 2, 3], [1, 2, 3], [1.0, 1.0, 1.0])

3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

In [424]:
Matrix(A)

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

Sparse factorization call the `CHOLMOD` module from `SuiteSparse`.

Community wrappers to MUMPS, Pardiso, HSL linear solvers.

## Package management

Julia's package manager is `Pkg` (https://julialang.github.io/Pkg.jl/v1/).

In [425]:
using Pkg

Packages are organized into **environments**.

An **environment** is a set of packages.

### Install / remove packages

Install a package with `Pkg.add`

In [426]:
Pkg.add("HSL")

   Resolving package versions...
    Updating `~/Bureau/Angleterre/presentation/Project.toml`
  [34c5aeac] + HSL v0.3.5
    Updating `~/Bureau/Angleterre/presentation/Manifest.toml`
  [34c5aeac] + HSL v0.3.5
  [40b5814e] + METIS4_jll v400.0.301+0
⌅ [656ef2d0] + OpenBLAS32_jll v0.3.17+0
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`


Update a package

In [427]:
Pkg.update("HSL")

    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/Bureau/Angleterre/presentation/Project.toml`
  No Changes to `~/Bureau/Angleterre/presentation/Manifest.toml`


Remove a package

In [428]:
Pkg.rm("HSL")

    Updating `~/Bureau/Angleterre/presentation/Project.toml`
  [34c5aeac] - HSL v0.3.5
    Updating `~/Bureau/Angleterre/presentation/Manifest.toml`
  [34c5aeac] - HSL v0.3.5
  [40b5814e] - METIS4_jll v400.0.301+0
  [656ef2d0] - OpenBLAS32_jll v0.3.17+0


### Projects and `Project.toml`

> The project file describes the project on a high level, for example the package/project dependencies and compatibility constraints are listed in the project file.

The `Project.toml` file contains the list of all packages in that environment and compatibility requirements (if any).

In [429]:
; cat Project.toml

[deps]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
HarwellRutherfordBoeing = "ce388394-9b3f-5993-a911-eb95552e4f2e"
ILUZero = "88f59080-6952-5380-9ea5-54057fb9a43f"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LimitedLDLFactorizations = "f5a24dde-3ab7-510b-b81b-6a72c6098d3b"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MatrixMarket = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
SuiteSparseMatrixCollection = "ac199af8-68bc-55b8-82c4-7abd6f96ed98"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"


### Package versions and `Manifest.toml`

> The **exact set of packages and versions** in an environment is captured in a **manifest file** which can be checked into a project repository and tracked in version control

The `Manifest.toml` file contains the **exact version** of every installed package, including all hidden dependencies.

If your `Manifest.toml` file is the same, your package version are the same.

### Working with environments

From Julia: use `Pkg.activate`

In [430]:
# activate environment located in current folder
Pkg.activate(".")

  Activating project at `~/Bureau/Angleterre/presentation`


When using Julia from the command line
```bash
julia --project=. script.jl
```

### Re-using someone else's environment

First download and install all packages

In [431]:
Pkg.activate(".")  # activate environment
Pkg.instantiate()  # download and install packages

  Activating project at `~/Bureau/Angleterre/presentation`


Good to go!

## Code structure

### When starting a new project

* Create a new environment at the root of the repository
* Use version control on `Project.toml` and `Manifest.toml`

```
--docs/
--src/
--test/
Project.toml
Manifest.toml
README.md
```

## Code loading

https://docs.julialang.org/en/v1/manual/code-loading/

### Code inclusion

Code from a different file can be loaded

In [432]:
include("hello.jl")

Hello world! Current time is 1.670491276946224e9s


In [433]:
include("hello.jl")

Hello world! Current time is 1.670491278980637e9s


This causes the contents of the file to be evaluated in the global scope.

Your code gets executed every time you call `include`.

### Package loading

You can load packages with `import / using`

In [434]:
import Krylov
cg

cg (generic function with 2 methods)

In [435]:
Krylov.cg

cg (generic function with 2 methods)

`using` allows you to use exported names in the current namespace

In [436]:
using Krylov
cg

cg (generic function with 2 methods)

## Compilation and timing

In Julia code is compiled **just-in-time** => some compilation happens while you execute your code.

Be careful when timing code execution!

In [437]:
"""Compute the sum of the elements in a vector."""
function my_sum(u::Vector{T}) where{T}
    s = zero(T)
    for x in u
        s += x
    end
    return s
end

u = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
v = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0];

The first time a function is called, it is compiled.
Subsequent calls are fast.

In [438]:
@time my_sum(u)  # First time (with Int64): compilation happens
@time my_sum(u)  # Second time: no compilation

  0.019466 seconds (4.04 k allocations: 198.443 KiB, 99.79% compilation time)
  0.000005 seconds


55

In [439]:
@time my_sum(v)  # First time (with Float64): compilation happens
@time my_sum(v)  # Second time: no compilation

  0.014424 seconds (4.04 k allocations: 197.123 KiB, 99.68% compilation time)
  0.000006 seconds (1 allocation: 16 bytes)


55.0

### Timing code properly

If you only care about the result => compilation doesn't impact you.

If you care about execution time => compilation does impact you.

Possible fix:
* Run your function twice, time only the second execution
* Run your function on a small example, then on your real problem

### Command line execution

Everytime you run
```bash
julia --project=. hello.jl
```
Julia has to re-compile a part of your code.

Make sure what you're timing does not include compilation times!